import streamlit as st
import sqlite3
import pandas as pd
import os
import time

st.set_page_config(page_title="AI SOC Command Center", layout="wide", page_icon="🛡️")

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH = os.path.join(BASE_DIR, "data", "soc_alerts.sqlite")

# Simple RBAC Simulation
st.sidebar.title("🔐 Authentication")
role = st.sidebar.selectbox("Select Role", ["Level 1 Analyst", "Level 3 Admin"])

st.title("🛡️ Secure Operations Center (SOC)")
st.caption("Monitoring real-time streaming network logs flagged by LSTM and Isolation Forests.")

# Auto-refresh mechanism to simulate live Kibana dashboard
st.empty()
if st.button("Refresh Logs"):
    pass # Re-runs script

try:
    conn = sqlite3.connect(DB_PATH)
    
    # Check if table exists
    df = pd.read_sql_query("SELECT * FROM alerts ORDER BY timestamp DESC LIMIT 50", conn)
    
    if len(df) == 0:
        st.info("Log engine active. Waiting for AI to detect an anomaly in the Kafka stream...")
    else:
        st.subheader("🚨 Critical Machine Learning Anomalies")
        
        # Display high-level metrics
        col1, col2, col3 = st.columns(3)
        col1.metric("Total Flagged IPs", len(df['ip_address'].unique()))
        col2.metric("Total Exfiltrated Bytes Blocked", f"{df['bytes_transferred'].sum() / 1e6:.2f} MB")
        
        if role == "Level 3 Admin":
            col3.error("ADMIN OVERRIDE ACTIVE")
        else:
            col3.success("Analyst View Mode")

        # Interactive Table
        st.dataframe(df[['timestamp', 'ip_address', 'bytes_transferred', 'failed_logins', 'status']], use_container_width=True)
        
        st.divider()
        st.subheader("🤖 Autonomous Threat Response (Generated by RAG LangChain)")
        
        # Display the most recent autonomous incident response
        latest_response = df.iloc[0]
        st.error(f"**Target IP:** {latest_response['ip_address']}")
        st.markdown(latest_response['ai_incident_response'])
        
except sqlite3.OperationalError:
    st.warning("Database not found. Please ensure `src/soc_pipeline.py` is actively running to generate logs.")
except Exception as e:
    st.error(f"Error connecting to ElasticSearch Simulator (SQLite): {e}")
finally:
    if 'conn' in locals():
        conn.close()
